# Generated by Django 5.2.16 on 2026-09-28 15:41

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('raw_text', models.TextField()),
                ('chunk_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('is_active', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RunSQL(
            sql="CREATE INDEX ON knowledge_chunk USING hnsw (embedding vector_cosine_ops);",
            reverse_sql="DROP INDEX IF EXISTS knowledge_chunk_embedding_idx;",
        ),
    ]
